/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import javax.swing.JFrame;
import util.Util;
import kontroler.Kontroler;

/**
 *
 * @author student1
 */
public class FmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FmGlavna
     */
    public FmGlavna() {
        initComponents();
        
        postaviFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmPravnoLice = new javax.swing.JMenu();
        jmiPretragaPravnoLice = new javax.swing.JMenuItem();
        jmiUnosPravnoLice = new javax.swing.JMenuItem();
        jmRacun = new javax.swing.JMenu();
        jmiNoviRacun = new javax.swing.JMenuItem();
        jmPodesavanja = new javax.swing.JMenu();
        jmiParametriBaze = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmPravnoLice.setText("Pravno lice");

        jmiPretragaPravnoLice.setText("Pretraga pravnih lica");
        jmiPretragaPravnoLice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaPravnoLiceActionPerformed(evt);
            }
        });
        jmPravnoLice.add(jmiPretragaPravnoLice);

        jmiUnosPravnoLice.setText("Unos pravnog lica");
        jmiUnosPravnoLice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosPravnoLiceActionPerformed(evt);
            }
        });
        jmPravnoLice.add(jmiUnosPravnoLice);

        jMenuBar1.add(jmPravnoLice);

        jmRacun.setText("Racun");

        jmiNoviRacun.setText("Novi racun");
        jmiNoviRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNoviRacunActionPerformed(evt);
            }
        });
        jmRacun.add(jmiNoviRacun);

        jMenuBar1.add(jmRacun);

        jmPodesavanja.setText("Podesavanja");

        jmiParametriBaze.setText("Parametri baze");
        jmPodesavanja.add(jmiParametriBaze);

        jMenuBar1.add(jmPodesavanja);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosPravnoLiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosPravnoLiceActionPerformed
        // TODO add your handling code here:
        Kontroler.vratiInstancuKontrolera().setAktivanSK(Util.SK_UNOS_PL);
        FmPravnoLice fmpl = new FmPravnoLice(this, true);
        fmpl.setVisible(true);
    }//GEN-LAST:event_jmiUnosPravnoLiceActionPerformed

    private void jmiPretragaPravnoLiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaPravnoLiceActionPerformed
        // TODO add your handling code here:
        FmPrikazPravnihLica prikazi = new FmPrikazPravnihLica(this, true);
        prikazi.setVisible(true);
    }//GEN-LAST:event_jmiPretragaPravnoLiceActionPerformed

    private void jmiNoviRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNoviRacunActionPerformed
       FmRacun fmr = new FmRacun(this,true);
       fmr.setVisible(true);
    }//GEN-LAST:event_jmiNoviRacunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmPodesavanja;
    private javax.swing.JMenu jmPravnoLice;
    private javax.swing.JMenu jmRacun;
    private javax.swing.JMenuItem jmiNoviRacun;
    private javax.swing.JMenuItem jmiParametriBaze;
    private javax.swing.JMenuItem jmiPretragaPravnoLice;
    private javax.swing.JMenuItem jmiUnosPravnoLice;
    // End of variables declaration//GEN-END:variables

    private void postaviFormu() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
}
