/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Mesto;
import domen.PravnoLice;
import gui.komponente.TblModelPravnoLice;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import util.Util;
import kontroler.Kontroler;

/**
 *
 * @author student1
 */
public class FmPrikazPravnihLica extends javax.swing.JDialog {

    /**
     * Creates new form FmPrikazPravnihLica
     */
    public FmPrikazPravnihLica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        centrirajFormu();
        popuniComboPravnaLica();
        popuniTabeluPravnaLica();
        srediTabeluPravnaLica();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcomboPravnaLica = new javax.swing.JComboBox();
        jbtnDetalji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPravnaLica = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Registrovana pravna lica: ");

        jcomboPravnaLica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnDetalji.setText("Detalji");
        jbtnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDetaljiActionPerformed(evt);
            }
        });

        jtblPravnaLica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Naziv", "Maticni broj", "PIB", "Datum osnivanja", "Sediste ", "Adresa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblPravnaLica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcomboPravnaLica, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 136, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcomboPravnaLica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDetalji))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDetaljiActionPerformed
        // TODO add your handling code here:
//        FmPravnoLice fpl = new FmPravnoLice(null, true, (PravnoLice)jcomboPravnaLica.getSelectedItem());
//        fpl.setVisible(true);
        Kontroler.vratiInstancuKontrolera().setAktivanSK(Util.SK_IZMENA_PL);
        PravnoLice pl = (PravnoLice) jcomboPravnaLica.getSelectedItem();
        Kontroler.vratiInstancuKontrolera().getMapa().put("pl_izabran", pl);
        FmPravnoLice fpl = new FmPravnoLice(null, true);
        fpl.setVisible(true);
    }//GEN-LAST:event_jbtnDetaljiActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        popuniComboPravnaLica();
        popuniTabeluPravnaLica();
        srediTabeluPravnaLica();
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDetalji;
    private javax.swing.JComboBox jcomboPravnaLica;
    private javax.swing.JTable jtblPravnaLica;
    // End of variables declaration//GEN-END:variables

    private void popuniComboPravnaLica() {
        jcomboPravnaLica.removeAllItems();

        try {
            List<PravnoLice> lpl = Kontroler.vratiInstancuKontrolera().vratiListuPravnihLica();
            for (PravnoLice pl : lpl) {
                jcomboPravnaLica.addItem(pl);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void popuniTabeluPravnaLica() {
        List<PravnoLice> lpl;
        try {
            lpl = Kontroler.vratiInstancuKontrolera().vratiListuPravnihLica();
//        TableModel tm =  jtblPravnaLica.getModel();
//        DefaultTableModel dtm = (DefaultTableModel) tm;
//        
//        for (PravnoLice pl : lpl) {
//            Object[] red = new Object[6];
//            red[0] = pl.getNaziv();
//            red[1] = pl.getMaticniBroj();
//            red[2] = pl.getPib();
//            red[3] = pl.getDatumOsnivanja();
//            red[4] = pl.getMestoSediste();
//            red[5] = pl.getOpstinaSediste()+" "+pl.getUlicaSediste();
//            dtm.addRow(red);
//        }
            jtblPravnaLica.setModel(new TblModelPravnoLice(lpl));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FmPrikazPravnihLica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FmPrikazPravnihLica.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void srediTabeluPravnaLica() {
        JComboBox jcpl = new JComboBox<Mesto>();
        jcpl.setModel(new DefaultComboBoxModel(Kontroler.vratiInstancuKontrolera().vratiListuMesta().toArray()));

        TableColumnModel tcm = jtblPravnaLica.getColumnModel();
        TableColumn tc = tcm.getColumn(4);
        tc.setCellEditor(new DefaultCellEditor(jcpl));
    }

    private void centrirajFormu() {
        setLocationRelativeTo(null);
    }
}
